{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "percona-valkey.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "percona-valkey.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "percona-valkey.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    {{- if .Values.networkPolicy.extraEgress }}
    - Egress
    {{- end }}
  ingress:
    - ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
        {{- if .Values.tls.enabled }}
        - port: {{ .Values.tls.port }}
          protocol: TCP
        {{- end }}
        {{- if eq .Values.mode "cluster" }}
        - port: {{ .Values.cluster.busPort }}
          protocol: TCP
        {{- end }}
        {{- if .Values.metrics.enabled }}
        - port: {{ .Values.metrics.port }}
          protocol: TCP
        {{- end }}
      {{- if not .Values.networkPolicy.allowExternal }}
      from:
        - podSelector: {}
      {{- end }}
    {{- with .Values.networkPolicy.extraIngress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.networkPolicy.extraEgress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
