{{- if and .Values.metrics.enabled .Values.metrics.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "percona-valkey.fullname" . }}
  namespace: {{ .Values.metrics.podMonitor.namespace | default .Release.Namespace }}
  labels:
    {{- include "percona-valkey.labels" . | nindent 4 }}
    {{- with .Values.metrics.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "percona-valkey.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- if .Values.metrics.podMonitor.sampleLimit }}
  sampleLimit: {{ .Values.metrics.podMonitor.sampleLimit }}
  {{- end }}
  {{- if .Values.metrics.podMonitor.targetLimit }}
  targetLimit: {{ .Values.metrics.podMonitor.targetLimit }}
  {{- end }}
  {{- with .Values.metrics.podMonitor.podTargetLabels }}
  podTargetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  podMetricsEndpoints:
    - port: metrics
      interval: {{ .Values.metrics.podMonitor.interval }}
      {{- if .Values.metrics.podMonitor.honorLabels }}
      honorLabels: true
      {{- end }}
      {{- with .Values.metrics.podMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.podMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
