{{- if include "percona-valkey.externalAccessCluster" . }}
{{- if eq .Values.externalAccess.service.type "NodePort" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "percona-valkey.fullname" . }}
  labels:
    {{- include "percona-valkey.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "percona-valkey.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "percona-valkey.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "percona-valkey.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "percona-valkey.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "percona-valkey.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "percona-valkey.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
