{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "percona-valkey.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "percona-valkey.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.auth.password }}
  valkey-password: {{ .Values.auth.password | b64enc | quote }}
  {{- else }}
  valkey-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
{{- end }}
