{{- if eq .Values.mode "sentinel" }}
{{- $fullname := include "percona-valkey.fullname" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-sentinel-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "percona-valkey.labels" . | nindent 4 }}
    app.kubernetes.io/component: sentinel
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: sentinel
      port: {{ .Values.sentinel.port }}
      targetPort: sentinel
      protocol: TCP
  selector:
    {{- include "percona-valkey.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: sentinel
{{- end }}
