{{- if or (and (eq .Values.mode "standalone") (gt (int .Values.standalone.replicas) 1)) (and (eq .Values.mode "sentinel") (gt (int .Values.sentinel.replicas) 1)) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "percona-valkey.fullname" . }}-read
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "percona-valkey.labels" . | nindent 4 }}
    app.kubernetes.io/component: read
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ .Values.service.loadBalancerClass }}
  {{- end }}
  ports:
    - name: valkey
      port: {{ .Values.service.port }}
      targetPort: valkey
      protocol: TCP
      {{- if .Values.service.appProtocol }}
      appProtocol: {{ .Values.service.appProtocol }}
      {{- end }}
    {{- if .Values.tls.enabled }}
    - name: valkey-tls
      port: {{ .Values.tls.port }}
      targetPort: valkey-tls
      protocol: TCP
      {{- if .Values.service.appProtocol }}
      appProtocol: {{ .Values.service.appProtocol }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "percona-valkey.selectorLabels" . | nindent 4 }}
{{- end }}
