apiVersion: v1
kind: Service
metadata:
  name: {{ include "percona-valkey.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "percona-valkey.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: valkey
      port: {{ .Values.service.port }}
      targetPort: valkey
    {{- if eq .Values.mode "cluster" }}
    - name: cluster-bus
      port: {{ .Values.cluster.busPort }}
      targetPort: cluster-bus
    {{- end }}
  selector:
    {{- include "percona-valkey.selectorLabels" . | nindent 4 }}
