{{- if .Values.autoscaling.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "percona-valkey.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "percona-valkey.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "percona-valkey.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.autoscaling.vpa.updateMode | quote }}
  resourcePolicy:
    containerPolicies:
      - containerName: valkey
        {{- with .Values.autoscaling.vpa.controlledResources }}
        controlledResources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.autoscaling.vpa.minAllowed }}
        minAllowed:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.autoscaling.vpa.maxAllowed }}
        maxAllowed:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
